language: node_js
node_js:
  - "0.12"
sudo: false
before_install:
  - "git clone https://github.com/Samsung/jalangi2 ~/jalangi2 && (cd ~/jalangi2; npm install)"
  - "git clone https://github.com/dai-shi/benchmark-octane.git ~/octane"
env:
  - jalangi=~/jalangi2 octane=~/octane
addons:
  apt:
    packages:
    - python-software-properties
    - python
    - make
notifications:
  email: false